name: Labeler

on:
  # We need pull_request_target to be able to add labels to PRs from forks.
  # Only allow pull_request_target when targeting main, not some historical branch.
  #
  # Make sure to don't introduce explicit checking out and installing/running
  # untrusted user code into this workflow!
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths-ignore: [.github]

  # To allow testing PRs that change workflows.
  # May be triggered together with pull_request_target, it's OK.
  pull_request:
    types: [opened, synchronize, reopened]
    paths: [.github]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    # Do not auto-label nightly builds PR
    if: ${{ github.event.pull_request.number != 26921 }}
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
